name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t saadaabdennour02/demo-express-app .

      - name: Publish image to Docker Hub
        run: docker push saadaabdennour02/demo-express-app:latest

  deploy:
    needs: build
    runs-on: self-hosted  # Replace with your self-hosted runner name
    steps:
      - name: Pull image from Docker Hub
        run: docker pull saadaabdennour02/demo-express-app:latest

      - name: Delete old container
        run: |
          docker stop demo-express-app || true
          docker rm demo-express-app || true

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name demo-express-app saadaabdennour02/demo-express-app:latest
